### ISSUE TITLE
Опечатка в readme 

### ISSUE THREAD

**Issue by Bu4ak** [Ratiborro/url-availability#2]
выглядит так как будто не хватает `new` и `//` в url

Сейчас так
```php
$checker = UrlAvailability(['https:ratibor-korobin.ru', 'https://vk.com']);
```
есть подозрение, что должно быть
```php
$checker = new UrlAvailability(['https://ratibor-korobin.ru', 'https://vk.com']);
```

**Comment by Ratiborro** [comment]
Спасибо, исправил))
Вообще пакет для теста делал, но это секрет ;-)

**Comment by Bu4ak** [comment]
Можно писать в сообщении коммита 
Closes #2 
Где цифра это номер issue и тогда будет привязка. И issue автоматически закроется. Вдруг ты не знал)
